[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.28"
evm_version = 'cancun'
optimizer = true
optimizer_runs = 1000
via_ir = true

[rpc_endpoints]
mainnet = "${RPC_URL}"


[fmt]
line_length = 80