[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_sol = true
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.production]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_sol = true
evm_version = 'cancun'
optimizer = true
optimizer_runs = 1000
via_ir = true

[rpc_endpoints]
mainnet = "${RPC_URL}"


[fmt]
line_length = 80