[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.28"
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 1000
via_ir = true

[rpc_endpoints]
# Public RPC endpoint
mainnet = "https://eth.llamarpc.com"


[fmt]
line_length = 80